### PR TITLE
Add access tags to highway=path

### PR DESCRIPTION
**Pull request by systemed**
If you're recommending highway=path (which I'd discourage: http://www.openstreetmap.org/user/Richard/diary/20333, https://wiki.openstreetmap.org/wiki/Duck_tagging) then bicycle=yes is absolutely essential - otherwise, renderers and routers have no idea that it's a path that bikes can use, not just a footpath.

### CODE REVIEW

**Comment by YaroShkvorets** [comment]
The more I think about it the more I tend to agree. Perhaps we should indeed change tagging scheme for pathways that are mostly used for cycling to highway=cycleway.
Been using OsmAnd+ for mapillary lately and it kinda doesn't make sense that 3m wide MUPs are shown on the map identical to barely visible cow paths nearby.
What do you think @heatshear @DenisCarriere ?

**Comment by james2432** [comment]
more details=better. It's like tagging highway=road vs highway=residential or highway=motorway. So much more can be derived from it

**Comment by heatshear** [comment]
I haven't consulted the wiki in great detail (only the links shared above), so this is a rather uninformed opinion. Take that for what it's worth.

If the tag on major paths (like Ottawa River MUP) is highway = cycleway, then would you have to tag access = pedestrian (or something like that). To me, cycleway implies bikes only, but the paths are intended to be multi-use. So, it's nice enough to call it a cycleway if you bike, but that just passes the problem on to pedestrian route planning.

I do agree completely that highway = path is pretty much useless on its own... I guess it tells me that there's a way through, but it could be some rocky swampy goat trail, or a 4m wide asphalt strip. Must be used with access, surface, width, and perhaps smoothness to be meaningful.

**Comment by james2432** [comment]
oh I agree with MUP (multi use pathes) being tagged as highway=path, but also add the access tags:
foot=yes 
bicycle=yes
Unless it is a bicycle only path, I wouldnt tag it as highway=cycleway
http://wiki.openstreetmap.org/w/index.php?title=Key:access&mobileaction=toggle_view_desktop#Land-based_transportation

**Comment by DenisCarriere** [comment]
I'm 👍 for using `highway=cycleway` for MUP's.

Looking at [`highway=cycleway`](http://wiki.openstreetmap.org/wiki/Tag:highway=cycleway?uselang=en-US) you can also include `foot=yes/designated` & `segregated=no` to allow pedestrian traffic. Might be the best option.

image

**Comment by DenisCarriere** [comment]
> but it could be some rocky swampy goat trail, or a 4m wide asphalt strip

Feels like when adding `highway=cycleway` you will "expect" a 4m wide asphalt strip and not a swampy goat trail (which `highway=path` might indicate).

**Comment by DenisCarriere** [comment]
👍 using `highway=cycleway` + other tags for MUP

**Comment by james2432** [comment]
Is it really a cycleway, when bikers prefer to use the Riverside parkway itself instead of the MUP? :P

**Comment by DenisCarriere** [comment]
True.. but this looks like a `highway=cycleway` and not a swampy rocky path 😛 

https://www.mapillary.com/app/?lat=45.39408055555555&lng=-75.69725&z=18.92259454240824&focus=photo&pKey=2PPDMLHFI5XzhZHQUco3lA
image

**Comment by DenisCarriere** [comment]
Also this:

https://www.mapillary.com/app/?lat=45.3895583333333&lng=-75.76453333333336&z=17&focus=photo&pKey=ssoxYWJZGKZ7h41eJf-A1Q

image

**Comment by YaroShkvorets** [comment]
Duck test IMO is the right approach.

When I come to a new city and want to go for a bike ride I'd like to open the map and note all the "blue" bike pathways. For our own map/routing app we can obviously take all the other tags into account and color them however we like but we won't be able to change behavior of all the other renderers and routers out there. 
Like here for example, in default OSM style, you see blue way and you know where you want to go on your bike:
image

If all those pathways were red (highway=path) it'd be pretty confusing to figure out which is the most bike-friendly at a glance.
 
So IMO we should go with highway=cycleway for all bike-first MUPs.

**Comment by DenisCarriere** [comment]
Merged this, however I'm moving this toward the new YAML schema, we can modify this later.

Adding `bicycle=yes` is an improvement, however it might be better to use `highway=cycleway`.

**Pull request merged**
